title: Kinship and Belonging
subtitle: Keywords for Black Louisiana
header: assets/figures/Icon-02.png
gallery: True



# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  keywords: # name of collection
    output: true # makes sure pages are output as html files
    layout: "keywords_item" # the layout for the pages to use
    metadata:
      source: "keywords.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/keywords" # path to the directory of images within `_data`
  # Team collection used to enumerate project team members in '_team' folder
  team:
    output: false
 
  keywords_descriptions:
    output: true
    layout: "facet_page_layout"
    metadata:
      source: "keywords_descriptions.csv"
  people:
    output: true
    layout: "person_description"
    metadata:
      source: "k4blpeople.csv"

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: "/search/index.json" # file the index will get written to
    collections:
      keywords:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - pid
          - label
          - filing_date
          - full_index
          - doc_origin
          - language
          - archive
          - governing_body
          - names_black
          - names_white
          - names_native
          - doc_type
          - keywords




# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: "About Us"
    sub:
      - label: "Project"
        link: "/about/"
      - label: "Team"
        link: "/team/"
      - label: "Contact Us"
        link: "/contact/"
  - label: "Discover"
    sub:
      - label: "Documents"
        link: "/collection/"
      - label: "Keywords"
        link: "/keywords_descriptions/abuse.html"
      - label: "People"
        link: "/people/"
  - label: "Resources"
    sub:
      - label: "Bibliography"
        link: "/bibliography/"
      - label: "Documentation"
        link: "/documentation"
      - label: "Contact Us"
        link: "/contact/"
  - label: "Search"
    link: "/search/"

