title: Kinship and Belonging
subtitle: Keywords for Black Louisiana
authors:
  Chenise:
    name: Chenise Calhoun
    github: chenisecal429
  Jamya:
    name: Jamya Davis
    github: jdcherelle
  Ellie:
    name: Ellie Palazzolo
    github: egpalazzolo
description: 'Kinship and Longing: Keywords for Black Louisiana brings to light evidence of Black life and Black history through annotated transcriptions and translations of French and Spanish colonial documents from 18th century Louisiana'
baseurl: "/keywords"
gallery: True



# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  keywords: # name of collection
    output: true # makes sure pages are output as html files
    layout: "keywords_item.html" # the layout for the pages to use
    metadata:
      source: "keywords.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/keywords" # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: "/search/index.json" # file the index will get written to
    collections:
      keywords:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - pid
          - label
          - filing_date
          - full_index
          - doc_origin
          - language
          - archive
          - governing_body
          - names_black
          - names_white
          - names_native
          - doc_type
          - keywords




# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: "About Us"
    link: "/about/"
  - label: "Our Team"
    link: "/team/"
 # - label: "Documents"
 #   sub:
 #     - label: "Parallax Images"
 #       link: "/exhibits/parallax/"
 #     - label: "Image References"
 #       link: "/exhibits/references/"
 #     - label: "Subset Collection"
 #       link: "/exhibits/subset/"
  - label: "Documents"
    link: "/collection/"
  - label: "Search"
    link: "/search/"
  - label: "Contact Us"
    link: "/contact/"

