title: Keywords for Black Louisiana
subtitle: 
header: /assets/figures/Icon-02.png
gallery: True
url: https://docs.k4bl.org

# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  keywords: # name of collection
    output: true # makes sure pages are output as html files
    layout: "keywords_item" # the layout for the pages to use
    metadata:
      source: "keywords.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/keywords" # path to the directory of images within `_data`
  keywords_descriptions:
    output: true
    layout: "facet_page_layout"
    metadata:
      source: "keywordsglossary.csv"
  people:
    output: true
    layout: "person_description"
    metadata:
      source: "k4blpeople.csv"
  # Team collection used to enumerate project team members in '_team' folder
  team:
    output: false

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: "/search/index.json" # file the index will get written to
    collections:
      keywords:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - pid
          - label
          - lhc_filing_date
          - full_index
          - lhc_doc_origin
          - language
          - lhc_archive
          - lhc_source
          - names_black
          - names_white
          - names_native
          - lhc_doc_type
          - keywords
          - abstract
      keywords_descriptions:
        content: false
        fields:
          - pid
          - label
          - Keyword
          - Description
          - "Main Bias Set Records"

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: "About"
    sub:
      - label: "The Project"
        link: "/about/"
      - label: "The Journey"
        link: "/journey/"
      - label: "The Team"
        link: "/team/"
      - label: "KCCAB"
        link: "/kccab/"
      - label: "Contact Us"
        link: "/contact/"
  - label: "Discover"
    sub:
      - label: "Documents"
        link: "/collection/"
      - label: "Keywords"
        link: "/keywords_descriptions/"
      - label: "People"
        link: "/people/"
  - label: "Resources"
    sub:
      - link: "/history/"
        label: "History"
      - label: "Bibliography"
        link: "/bibliography/"
      - label: "Reflections"
        link: "/reflections/"
      - label: "Documentation"
        link: "https://github.com/lxcprojects/k4bl"
      - label: "Contact Us"
        link: "/contact/"
  - label: "Stories"
    link: "https://stories.k4bl.org"
  - label: "Search"
    link: "/search/"
